<a href="https://colab.research.google.com/github/AadityaAdh/tf_math/blob/main/tf_math.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf

#abs function

to generate absolute value ie make it positive

In [ ]:
x=tf.constant([-2.44,3.11,-11])
tf.abs(x)

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([ 2.44,  3.11, 11.  ], dtype=float32)>

#argmax :find the index of maximum value

Returns the index with the largest value across axes of a tensor

tf.math.argmax(


    input,
    axis=None,
    output_type=tf.dtypes.int64,
    name=None
)

input:

	A Tensor.
axis:

	An integer, the axis to reduce across. Default to 0.
output_type:

	An optional output dtype (tf.int32 or tf.int64). Defaults to tf.int64.
name:

	An optional name for the operation.

In [ ]:
#for a 1d tensor
a=tf.constant([1,2,3,55,4])
#here index of highest value is 3
tf.math.argmax(
    a,
    axis=0,
    output_type=tf.dtypes.int64,
    name=None
)

<tf.Tensor: shape=(), dtype=int64, numpy=3>

#Axis in tensorflow and numpy as well
shape garda(x,y,z)
yesari aauxa value

so x vanae ko axis 0 so columns

y vanae ko axis 1 so row

z vanae ko axis 2 so matrix

In [ ]:
b=tf.constant([
    [1,2,3],
    [3,4,5]
])
b.shape

TensorShape([2, 3])

In [ ]:
#axis is 0 means row
#row ko 1st 1st element compare garni
#1st row ma 1 ra 2nd row ma 3
#1 ra 2 vanya different column ho row haina
#1 ra 3 vanya chai different row ho
tf.math.argmax(b,0)

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([1, 1, 1])>

In [ ]:
tf.math.argmax(b,1)

<tf.Tensor: shape=(2,), dtype=int64, numpy=array([2, 2])>

In [ ]:
tensor_three_d=tf.constant([
    [
        [1,2,0],
        [3,5,-1]
    ],
    [
        [10,2,0],
        [1,2,0]
    ]
])


In [ ]:
#finding highest in columns so axis is 2
#axis 2 garda duitai matrix ko lagi hunxa aani aani reslut yeuta matrix  form ma aauxa
# 1st matrix ko 3 ootaa column element herum
#1,2,0 xa yesma thulo 2 so index=1
#aani secund ma thulo 5 index 1
#so yeuta matrix ko value[1,1] vayo
tf.math.argmax(tensor_three_d,2)

<tf.Tensor: shape=(2, 2), dtype=int64, numpy=
array([[1, 1],
       [0, 1]])>

In [ ]:
#in rows
#1,3 ma 3 thulo so index=1 same for other in each matrix
#2,5 ma 5 thuolo index=1
#0 ra -1 ma 0 thulo so index=0

tf.math.argmax(tensor_three_d,1)

<tf.Tensor: shape=(2, 3), dtype=int64, numpy=
array([[1, 1, 0],
       [0, 0, 0]])>

In [ ]:
tf.math.argmax(tensor_three_d,0)
#yo vanya chai matrix vs matrix
#m1,m2 ko pratyek corresponding element herni ,m1 ,m2 vanya yo vitra ko duita element
#yedi m1 ko thulo xa vanae index 0 return m2 xa  vanae index1

<tf.Tensor: shape=(2, 3), dtype=int64, numpy=
array([[1, 0, 0],
       [0, 0, 1]])>

#sin and asin functions

The tf.math.asin operation returns the inverse of tf.math.sin, such that if y = tf.math.sin(x) then, x = tf.math.asin(y).

In [ ]:
# Note: [1.047, 0.785] ~= [(pi/3), (pi/4)]
x = tf.constant([1.047, 0.785])
y = tf.math.sin(x) # [0.8659266, 0.7068252]

tf.math.asin(y) # [1.047, 0.785] = x

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.047, 0.785], dtype=float32)>

#square root



In [ ]:
x = tf.constant([[4.0], [16.0]])
tf.math.sqrt(x)

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[2.],
       [4.]], dtype=float32)>

In [ ]:
#negative ko square root garyo vanae nan vanae ra aauxa if it is specififed as integer
y = tf.constant([[-4.0], [16.0]])
tf.math.sqrt(y)

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[nan],
       [ 4.]], dtype=float32)>

In [ ]:
#but if you say  it as complex number then sabbai ko result i+j ko terma ma aauxa
z = tf.constant([[-1.0], [16.0]], dtype=tf.complex128)
tf.math.sqrt(z)

<tf.Tensor: shape=(2, 1), dtype=complex128, numpy=
array([[0.+1.j],
       [4.+0.j]])>

#Add

tf.math.add(


    x, y, name=None
)


2 oota tensors x and y


In [ ]:
a=tf.constant([1,2,3,4])
b=tf.constant([5,6,7,8])
tf.math.add(a,b)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 6,  8, 10, 12], dtype=int32)>

In [ ]:
#adding out of dimension tensors
a=tf.constant([1,2,3,4])
b=tf.constant([5])
tf.math.add(a,b)
#same if you want to do for 2d,3d..... tensors
#iy you want to add each element by certain number

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([6, 7, 8, 9], dtype=int32)>

#Divide

In [ ]:
x = tf.constant([16, 12, 11])
y = tf.constant([4, 6, 2])
tf.math.divide(x,y)



<tf.Tensor: shape=(3,), dtype=float64, numpy=array([4. , 2. , 5.5])>

#tf.math.divide_no_nan



Computes a safe divide which returns 0 if y (denominator) is zero.vanya yedi kunai lai divide garda divide by zero(x/0) vaya ra infinite aauni vayo vanae tyo infinite na vai zero banai dinxa



In [ ]:
x = tf.constant([16, 12, 11])
y = tf.constant([4, 0, 2])
tf.math.divide_no_nan(x,y)

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([4. , 0. , 5.5])>

In [ ]:
#yedi divide matra garya vayae infinite aauxa
x = tf.constant([16, 12, 11])
y = tf.constant([4, 0, 2])
tf.divide(x,y)

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([4. , inf, 5.5])>

Multiply

In [ ]:
x = tf.constant(([1, 2, 3, 4]))
tf.math.multiply(x, x)


<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 1,  4,  9, 16], dtype=int32)>

#tf.math.multiply_no_nan


Computes the product of x and y and returns 0 if the y is zero, even if x is NaN or infinite.

kei gari infinite aauni vayae vanae multiply garda tellai 0 banauna

In [ ]:
#multiplication but not of like matrix instead direct multiplication
a=tf.constant([[5,3,6,6,4,6]])
b=tf.constant([[7],[5],[3]])
print(a.shape)
print(b.shape)

(1, 6)
(3, 1)


In [ ]:
#herni ho vanae  multiply ta garna ta mildaina matrix multiplication haina hai feri simple multiplication
#tara tensorflow lae garxa
#by duplicating


In [ ]:
tf.math.multiply(a,b)

<tf.Tensor: shape=(3, 6), dtype=int32, numpy=
array([[35, 21, 42, 42, 28, 42],
       [25, 15, 30, 30, 20, 30],
       [15,  9, 18, 18, 12, 18]], dtype=int32)>

#Equal tf.math.equal


Returns the truth value of (x == y) element-wise.

tf.math.equal(


    x, y, name=None
)

element-wise equality comparison, returning a Tensor of boolean values.

In [ ]:
x = tf.constant([2, 4])
y = tf.constant(2)
tf.math.equal(x, y)


<tf.Tensor: shape=(2,), dtype=bool, numpy=array([ True, False])>

In [ ]:
x = tf.constant([2, 4])
y = tf.constant([2, 4])
tf.math.equal(x, y)


<tf.Tensor: shape=(2,), dtype=bool, numpy=array([ True,  True])>

#Power of Each Element tf.math.pow


Computes the power of one value to another.

tf.math.pow(


    x, y, name=None
)



In [ ]:
x = tf.constant([[2, 2], [3, 3]])
y = tf.constant([[8, 16], [2, 3]])
tf.pow(x, y)  # [[256, 65536], [9, 27]]

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[  256, 65536],
       [    9,    27]], dtype=int32)>

#sum within itself  tf.math.reduce_sum


Computes the sum of elements across dimensions of a tensor.

sum garna aafno elements bich ma
row column jun axis ma ni garna milxa

tf.math.reduce_sum(


    input_tensor, axis=None, keepdims=False, name=None
)
axis diye navanae sabbai ko sum gardinxa as numpy
axis dini aai tei aanusar matrai garxa

In [ ]:
tensor_two_d=tf.constant([
    [1,2],
     [3,4]])
print(tensor_two_d)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [ ]:
tf.math.reduce_sum(
    tensor_two_d, axis=0
)
 #1 ra2 vanae rajhukkna vayae na
 #1 ra 3 ho different rows
 #axis=0 vanya row

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([4, 6], dtype=int32)>

In [ ]:
tf.math.reduce_sum(
    tensor_two_d, axis=1
)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 7], dtype=int32)>

#sigmoid tf.math.sigmoid



Computes sigmoid of x element-wise.

tf.math.sigmoid(

  
    x, name=None
)

In [ ]:
x = tf.constant([0.0, 1.0, 50.0, 100.0])
tf.math.sigmoid(x)



<tf.Tensor: shape=(4,), dtype=float32, numpy=array([0.5      , 0.7310586, 1.       , 1.       ], dtype=float32)>